services:
  yt:
    image: yk:latest
    container_name: yk-yt
    restart: unless-stopped
    network_mode: host
    tty: true
    stdin_open: true
    user: "1000"

    environment:
      # YK_PROXIES: socks5://127.0.0.1:1080
      YK_LOG_PATH: /out
      YK_DELAY: 300 # big delay for yt
      # YK_APPRISE: apprise.yml
      YK_SRC_LISTS: /tmp/yt.txt
    build:
      context: https://github.com/ntrrpt/yk.git
      args:
        # update yt-dlp/deps on every container start
        # (because google likes to break things)
        FORCE_UV_SYNC_ON_START: YES
    volumes:
      - ./:/out
      - ./yt.txt:/tmp/yt.txt

      # po token extractor plugin 
      # - ./bgutil-ytdlp-pot-provider.zip:/etc/yt-dlp/plugins/bgutil-ytdlp-pot-provider.zip

    command: ['--yta']

  tw:
    image: yk:latest
    container_name: yk-tw
    restart: unless-stopped
    tty: true
    stdin_open: true
    user: "1000"

    environment:
      YK_LOG_PATH: /out
      YK_DELAY: 15
      YK_SRC_LISTS: /tmp/tw.txt
    build:
      context: https://github.com/ntrrpt/yk.git
      args:
        # (and twitch sometimes too)
        FORCE_UV_SYNC_ON_START: YES
    volumes:
      - ./:/out
      - ./tw.txt:/tmp/tw.txt

    command: []

#  bgutil:
#    image: brainicism/bgutil-ytdlp-pot-provider
#    container_name: bgutil
#    network_mode: host
#    init: true
#    restart: unless-stopped