services:
  tw:
    container_name: tw

    image: yk-custom
    restart: unless-stopped
    tty: true

    environment:
      YK_DELAY: 15
      YK_INPUT: /list.toml
    build:
      context: https://github.com/ntrrpt/yk.git
    volumes:
      - ./:/out
      - ./lists/tw.toml:/list.toml

  yt:
    container_name: yt

    image: yk-custom
    restart: unless-stopped
    network_mode: host
    tty: true

    environment:
      YK_PROXIES: socks5://127.0.0.1:1080
      # gid/pid for non-root users
      GID: 1000 
      PID: 1000
      # big delay for youtube
      YK_DELAY: 300 
      YK_INPUT: /list.toml
    build:
      context: https://github.com/ntrrpt/yk.git
    volumes:
      - ./:/out
      - ./lists/yt.toml:/list.toml
      # ./cookies.txt:/cookies.txt
      # ./apprise.yml:/apprise.yml

      # po token extractor plugin (https://github.com/Brainicism/bgutil-ytdlp-pot-provider)
      # - ./bgutil-ytdlp-pot-provider.zip:/etc/yt-dlp/plugins/bgutil-ytdlp-pot-provider.zip

    # use 'yt-dlp' as checker and 'ytarchive' as recorder
    command: --chk dlp --rec yta

#  bgutil:
#    image: brainicism/bgutil-ytdlp-pot-provider
#    container_name: bgutil
#    network_mode: host
#    init: true
#    restart: unless-stopped